name = "Immersium"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2175a2bb4c6c21ece68ec56bc6038d1ff5fc8347ac203979f3024fc5c906a2e5"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/global_packs/required_data"
