name = "Immersium"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f980dc7352469c70d8b84aee41b0a1758874c21c3cc4d849f9486718779d902e"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "/global_packs/required_data"
