name = "Immersium"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b132513c815d8a80c5e5a9c9d631db5c47359aba88a1892668b255ae373ae61"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/global_packs/required_data"
