name = "Immersium"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ccb6464e302ea76e39c549ba5573828d51473188f1165586488f3461eb0a20b"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "/global_packs/required_data"
