name = "Immersium"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ab0a8f48289cf8f3265b0bcf6c094efb6db2487a390bd6b4e974e5be2920989"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/global_packs/required_datapacks"
