name = "Immersion Pack Updated"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6230dbaca16ea232c0b08714077f8df0a2af33811ea3050af02df746f5598d4a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2-beta.2"

[options]
acceptable-game-versions = ["1.19"]
datapack-folder = "/global_packs/required_datapacks"
