name = "Immersium"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "702a4ccb11cbade7afc8c2f4f857e418d0e84ffc2d7c08a3dffc232d548e9110"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/global_packs/required_data"
