name = "Immersion Pack Updated"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a193fa55fd89f252bf3d26eb461555179a42890534ab5b9bf0e8bfb54dc7f58"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2-beta.2"

[options]
acceptable-game-versions = ["1.19"]
datapack-folder = "/global_packs/required_datapacks"
