enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "GAP"
leavesCullingAmount = 1
includeMangroveRoots = true
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
everycomp = true
seasonsextras = true
farmersdelight = true
mythicmetals = true
forgottengraves = true
infinitybuttons = true
alloy_forgery = true
rotten = true
variantcraftingtables = true
improved_end = true
runes = true
twigs = true
comforts = true
blossom = true
bitsandchisels = true
snowyspirit = true
nethersdelight = true
create_enchantment_industry = true
byg = true
railways = true
variant_grindstones = true
milk = true
led = true
variant_bookshelves = true
variant_lanterns = true
netherflowers = true
snowrealmagic = true
scarves = true
andromeda = true
sulfurpotassiummod = true
spell_engine = true
creategoggles = true
naturalist = true
nightlights = true
consistency_plus = true
backpacked = true
techreborn = true
variantcomposters = true
create = true
culturaldelights = true
geodes = true
forgero = true
fluidbarrel = true
xps = true
tablesaw = true
aquatictorches = true
vsas = true
angling = true
minecraft = true
philipsruins = true
enderzoology = true
regions_unexplored = true
geocluster = true
woods_and_mires = true
ae2 = true
immersive_weathering = true
bosses_of_mass_destruction = true
creeperoverhaul = true
computercraft = true
villagersplus = true
expandeddelight = true
bushierflowers = true
packages = true
